# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
